// Ashish Kumar
// 2020kucp1008
// C program to implement insertion and printing the array in the preorder form i.e ascending order form which one of its application ...

//  NOTE : If you want to insert the two same value as it will skip , i.e  repetition of same values again will be skipped .
#include <stdio.h>
#include <stdlib.h>

struct binaryTree {
	int key;
	struct binaryTree *left, *right;
};
// creating an array which will help user to enter the value he want to insert ...
int *arr ;

// A  function to create a new binary  node
struct binaryTree* newNode(int item)
{
	struct binaryTree* temp = (struct binaryTree*)malloc(sizeof(struct binaryTree));
	temp->key = item;
	temp->left = temp->right = NULL;
	return temp;
}

// A  function to do inorder traversal of binary tree
void inorder(struct binaryTree* root)
{
	if (root != NULL) {
		inorder(root->left);
		printf("%d \n", root->key);
		inorder(root->right);
	}
}

/* A function to insert*/

struct binaryTree* insert(struct binaryTree* node, int key)
{
	/* If the tree is empty, return a new node */
	if (node == NULL)
		return newNode(key);

	if (key < node->key)
		node->left = insert(node->left, key);
	else if (key > node->key)
		node->right = insert(node->right, key);

	return node;
}
void print_tabs(int number)
{
    for (int i = 0; i < number; i++)
    {
        printf("\t");
    }
}
// here we are displaying the tree as generated by binary tree.. 
void display(struct binaryTree *ptr, int level)
{
    if (ptr == NULL)
    {
        print_tabs(level);
        printf("----<empty>----\n");
        return;
    }
    print_tabs(level);
    printf(" Value = %d\n", ptr->key);
    print_tabs(level);
    printf("left\n");
    display(ptr->left, level + 1);
    print_tabs(level);
    printf("right\n");
    display(ptr->right, level + 1);
    print_tabs(level);
    printf("done\n");
}
void display_all(struct binaryTree *ptr)
{
    display(ptr, 0);
}



int main()
{
    int n ;
    // enter the value of n such that it has maximum 5 subtree 
    printf("\nenter the value of n , number of values you want to insert in tree : ");
    scanf("%d",&n);
    arr = (int *)malloc(n*sizeof(int));
    printf("\nNow enter the values you want to insert in the tree .. ");
    // asking for user to insert the values 
    for(int i =0 ;i<n;i++)
    {
        printf("\nenter the %d value : ",i+1);
        scanf("%d",&arr[i]);
    }
    // insertion on the tree 
	struct binaryTree* root = NULL;
    // making the first value as tree root 
    root = insert(root,arr[0]);
    // now inserting all the values 
    for(int i =1;i<n;i++)
    {
        insert(root,arr[i]);
    }
    // displaying tree what binary generated 
    display_all(root);
	// print inoder traversal of the Binary
	inorder(root);

	return 0;
}